### ISSUE TITLE
[subtitles] [fr] MÉLENCHON : «POUR UNE MAJORITÉ PARLEMENTAIRE INSOUMISE AUX LÉGISLATIVES»

### ISSUE THREAD

**Issue by RobotInsoumis** [jlm2017/jlm-video-subtitles#344]
## MÉLENCHON : «POUR UNE MAJORITÉ PARLEMENTAIRE INSOUMISE AUX LÉGISLATIVES»

&nbsp;          | Info
--------------- | ---------------
**Date**        | Dimanche 30 avril 2017
**Durée**       | 0:09:16 :clock7:
**Langue**      | Français :fr:
**Vidéo**       | [Voir dans YouTube :arrow_upper_right:](https://www.youtube.com/watch?v=wsGkA4TXqyw)
**Sous-titres** | [Éditer dans YouTube :arrow_upper_right:](https://www.youtube.com/timedtext_editor?v=wsGkA4TXqyw&tab=captions&bl=vmp&action_mde_edit_form=1&lang=fr&ui=hd)

**Comment by youpidou** [comment]
J'ai relu et ajusté un peu les sous-titres, je ne sais pas comment faire le reste.

**Comment by spi-soustitrage** [comment]
Super.
Je viens de faire une relecture, j'ai passé la vidéo en "second review".
@youpidou je ne fais pas partie de ceux qui peuvent te faire passer en "collaborateur" (dès que l'un d'eux passera par là...). Mais si tu as besoin de relecture, tu peux me demander.

**Comment by youpidou** [comment]
@spi-soustitrage C'est gentil. Je vais voir pour avancer d'autres sous-titrages en attendant :-)

**Comment by spi-soustitrage** [comment]
:)
Et si tu veux t'essayer à la relecture, je viens ( enfin! ) de finir le sous-titrage de #316

Je pense que même si tu n'as pas le statut "collaborateur", tu dois pouvoir utiliser les labels et ainsi pouvoir indiquer aux autres où tu en es. Tu peux ainsi mettre plusieurs labels en même temps ( par ex "someone is working on this issue" et "writing in progress") et en enlever qu'un seul quand tu fais une pause suffisamment longue. 
Bref, fais comme chez toi.

**Comment by spi-soustitrage** [comment]
Et pour le statut de collaborateur, tu peux mettre un message de présentation par ici #17

**Comment by Sophie-Dube** [comment]
J'aimerais bien sous-titrer ça en Anglais mais je suis nouvelle et je ne comprends pas trop comment m'insérer alors mettons que je commence à faire ça tranquille chez moi sur un fichier txt et puis si qqn peut m'expliquer la suite...

**Comment by youpidou** [comment]
@spi-soustitrage 

Je ne sais pas trop comment faire la relecture officiellement, ni comment gérer les labels. Je crois que seuls les collaborateurs peuvent le faire. Je ne sais pas non plus bien comment demander le statut de collaborateur. Tout ce que je sais faire c'est aller sur Youtube et arranger les sous-titres.

Pour ça que je mets ce que j'ai à dire en commentaires, mais si on m'explique étape par étape je le ferai. Quand je me suis inscrite sur le site on m'a parlé d'une vidéo explicative mais celle-ci semble introuvable. Bon. Si un jour j'arrive à mieux maîtriser le fonctionnement de ce site qui est décidément pas intuitif du tout j'essaierai de faire un doc d'explications captures d'écran à l'appui. Sauf s'il y en a un mais j'ai pas l'impression.

**Comment by Sophie-Dube** [comment]
J'ai fait jusqu'à 3min54 secondes, je mets ça là... Je fais une pause!!!


Good evening Jean-Luc Mélenchon

Good evening

Thank you for accepting our invitation, it's your first interview since the first round of the presidential election. Last Sunday you seemed to find it hard to accept the results and your fourth place.

No, I waited until the result became clearer because as you may have noticed the gap in the end was smaller than it seemed in the beginning. And it's quite normal to wait for the results to stabilize before making any comments. The results for the three of us was around 7 million votes, for me it was a matter of 600 000 votes. Should I have had those votes, we would be facing each other for the second round, Mr Macron and myself. Therefore I was right to wait before speaking. And when I spoke I hadn't yet realized our strenght : 7 million votes but also we were ahead in tens of towns and many of the big cities. This gives me a most special responsability, I am not the man I was before. I represent that strenght, and the result of this election will not give any stability to the country. Both finalists gathered together only 45% of the actual votes, and many citizens (10 million) didn't vote. So the real political choice will take place in the legislative elections.
That's why I will personally lead that force that has gathered around me, so it becomes a parliamentary majority.

 Before the legislative elections there is a presidential second round and there is a choice to be made. In 2002 you had clearly asked people to vote for Jacques Chirac, why don't you do so now ? Marine Le Pen is different from Jean-Marie Le Pen ?

No, they're the same. There is no ambiguity in my position. My position is NOT « neither... nor.... ». I will not vote for the National Front . I am against the National Front. And I say to all the people who listen to me do not do that terrible mistake to vote for the Front National, because it would set the country on fire, it would put us in a kind of war, everybody looking into the cradles to check the nationalities, the religions... So, DON'T DO IT ! But things have changed since 2002. At that time we thought it was an accident, and since then the same thing happens over and over, at each election . We live under the threat of a second round with the Le Pen family, and everytime we are expected to... But let me remind you that during the regional elections I did just the same as now : I did NOT invoke the « Republican Front ».. It would be like giving a firefighter certificate to pyromaniacs.
I have nothing in common with the Republican Party, I have nothing in common with the Socialist Party, regarding political choices. Therefore, I tell everyone : use your intelligence, do what you have to do. Why ? Because I know my friends are parted in three groups : those who will vote Macron – and I respect that -, those who will abstain -and I respect that - , those who will vote white. And MY duty is to tell them, all of them, whatever you have decided, you can rest on me. You can rest on the Unbowed France, and I am ready to govern this country, if we obtain a parliamentary majority.	

Sorry to ask again, but you are ready to vote white ?

It's my own business and I won't tell you.
